### ISSUE TITLE
Wrong update rule for STEM cells 

### ISSUE THREAD

**Issue by maxiuw** [MeiBlundell/Stochastic_Tumor_Model#1]
Hi, 
I am currently doing research about the CA application and one of the CA I am using is for simulating tumor growth. I was trying to use your code, but in the end, I modified mine from another project. I run yours to see how it works and there is the main issue with STEM cells. If you plot the number of cells, you can see that after some time the amount falls to 0. It is impossible since, according to the article, STEM cells are being considered immortal. I had the same problem and the issue was that I was just checking values of the neighbors in the previous step, not the current step. Consider this situation:

if the cell a cell from the 1st row migrated to the 2nd row in the step n, if we are gonna update e.g. 3rd row, in the neighbors of one of the cells, the field was taken by the updated/new value -> cell which e.g. migrated, will be seen as an empty field and can be used for migration or splitting, when in the real world this field is already taken!!!

Idk if you are still using the code but if yes, that would be something to look into :) 

Cheers !

**Comment by MeiBlundell** [comment]
Hi @maxiuw ,

Nice catch, thanks for letting me know! If I decide to revise it again, I'll definitely work in a check for the current step. I'm glad you looked into my code, and good luck with your own project!

Happy New Year,
Mei
